#!/usr/bin/env node
import { readFileSync, writeFileSync } from "fs";
import { execSync } from "child_process";

const pkg = JSON.parse(readFileSync("package.json", "utf-8"));
let gitHash = "dev";
let gitDate = new Date().toISOString().split("T")[0];

try {
  gitHash = execSync("git rev-parse --short HEAD").toString().trim();
  gitDate = execSync("git log -1 --format=%cs").toString().trim();
} catch {
  // Not in a git repo
}

const content = `// Auto-generated by scripts/generate-version.js - do not edit
export const APP_VERSION = "${pkg.version}";
export const GIT_HASH = "${gitHash}";
export const GIT_DATE = "${gitDate}";
`;

writeFileSync("src/lib/version.ts", content);
console.log(`Generated version.ts: v${pkg.version} (${gitHash}, ${gitDate})`);
